export default {
  future: {
    hoverOnlyWhenSupported: true,
  },
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "vscode-bg": "#1A1A1A",
        "vscode-header": "#242424",
        "vscode-active": "#0D4A9E",
        "vscode-text": "#FFFFFF",
        "vscode-accent": "#0090F1",
        "nord-text-primary": "#FFFFFF",
        "nord-text-secondary": "#E6E6E6",
        "nord-text-error": "#FF3B3B",
        "nord-button-primary": "#0065C2",
        "nord-button-primary-hover": "#0078D4",
        "nord-button-secondary": "#595959",
        "nord-button-secondary-hover": "#6A6A6A",
        "nord-bg-card": "#2A2A2A",
        "nord-bg-hover": "#323232",
        "nord-bg-active": "#3D3D3D",
        "nord-bg-overlay": "rgba(0, 0, 0, 0.75)",
        "nord-bg-overlay-light": "rgba(0, 0, 0, 0.5)",
        "nord-load-low-bg": "#0B3B1F",
        "nord-load-low-text": "#4AFF91",
        "nord-load-medium-bg": "#2D4016",
        "nord-load-medium-text": "#B8FF84",
        "nord-load-warning-bg": "#3D3415",
        "nord-load-warning-text": "#FFE484",
        "nord-load-high-bg": "#3D1515",
        "nord-load-high-text": "#FF9494",
        "nord-load-critical-bg": "#4A1515",
        "nord-load-critical-text": "#FFBEBE",
        "nord-success-bg": "#0B3B1F",
        "nord-success-text": "#6EFFAB",
      },
    },
  },
  plugins: [],
};